# Generated by Django 4.2.16 on 2026-05-17 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=200, verbose_name='Institución')),
                ('degree', models.CharField(max_length=200, verbose_name='Título / Carrera')),
                ('field', models.CharField(blank=True, max_length=200, verbose_name='Especialidad / Área')),
                ('start_year', models.PositiveIntegerField(verbose_name='Año de inicio')),
                ('end_year', models.PositiveIntegerField(blank=True, help_text='Dejar vacío si está en curso', null=True, verbose_name='Año de fin')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Educación',
                'verbose_name_plural': 'Educación',
                'ordering': ['order', '-start_year'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200, verbose_name='Empresa / Organización')),
                ('position', models.CharField(max_length=200, verbose_name='Cargo / Rol')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('is_current', models.BooleanField(default=False, verbose_name='Trabajo actual')),
                ('description', models.TextField(verbose_name='Descripción / Logros')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Experiencia',
                'verbose_name_plural': 'Experiencias',
                'ordering': ['order', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Idioma')),
                ('level', models.CharField(choices=[('nativo', 'Nativo'), ('avanzado', 'Avanzado (C1/C2)'), ('intermedio', 'Intermedio (B1/B2)'), ('basico', 'Básico (A1/A2)')], max_length=20, verbose_name='Nivel')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Idioma',
                'verbose_name_plural': 'Idiomas',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('tagline', models.CharField(blank=True, help_text='Ej: Escritor y ensayista', max_length=200, verbose_name='Título profesional')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('location', models.CharField(blank=True, max_length=150, verbose_name='Ubicación')),
                ('bio', models.TextField(verbose_name='Sobre mí')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='cv/', verbose_name='Foto de perfil')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('twitter', models.URLField(blank=True, verbose_name='Twitter / X')),
                ('website', models.URLField(blank=True, verbose_name='Sitio web personal')),
            ],
            options={
                'verbose_name': 'Información personal',
                'verbose_name_plural': 'Información personal',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Título')),
                ('publisher', models.CharField(blank=True, max_length=200, verbose_name='Editorial / Medio')),
                ('year', models.PositiveIntegerField(verbose_name='Año')),
                ('url', models.URLField(blank=True, verbose_name='Enlace')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Publicación',
                'verbose_name_plural': 'Publicaciones',
                'ordering': ['order', '-year'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Habilidad')),
                ('category', models.CharField(choices=[('tecnicas', 'Habilidades técnicas'), ('blandas', 'Habilidades blandas'), ('otras', 'Otras')], default='tecnicas', max_length=20, verbose_name='Categoría')),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Básico'), (2, 'Elemental'), (3, 'Intermedio'), (4, 'Avanzado'), (5, 'Experto')], default=3, verbose_name='Nivel')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Habilidad',
                'verbose_name_plural': 'Habilidades',
                'ordering': ['order', 'name'],
            },
        ),
    ]
