# Generated by Django 4.2.16 on 2026-05-17 04:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('author', models.CharField(max_length=200, verbose_name='Autor')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Descripción')),
                ('pdf_file', models.FileField(upload_to='books/pdfs/', verbose_name='Archivo PDF')),
                ('cover_front', models.ImageField(blank=True, help_text='Imagen de la tapa del libro (opcional)', null=True, upload_to='books/covers/', verbose_name='Tapa')),
                ('cover_back', models.ImageField(blank=True, help_text='Imagen de la contratapa del libro (opcional)', null=True, upload_to='books/covers/', verbose_name='Contratapa')),
                ('published_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Año de publicación')),
                ('isbn', models.CharField(blank=True, max_length=20, verbose_name='ISBN')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visible')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Cargado')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'ordering': ['-created_at'],
            },
        ),
    ]
